// =============================================================================
// ScheduleServiceModal.js - Bottom-sheet modal for scheduling a future service
// Version: 2.0
// Last Updated: 2026-04-17
//
// PROJECT:      Rolodeck (project v0.22.8)
// FILES:        ScheduleServiceModal.js  (this file)
//               CustomerDetailScreen.js  (renders this modal)
//               storage.js               (addScheduledService)
//               scheduleSettings.js      (getScheduleSettings, generateSlots,
//                                          isWorkDay, nextWorkDay,
//                                          formatDuration, formatSlotLabel)
//               theme.js                 (useTheme)
//               typography.js            (FontSize)
//
// Copyright © 2026 ArdinGate Studios LLC. All rights reserved.
//
// ARCHITECTURE:
//   - Appointment type selector: "Service" / "Install" chips at the top
//   - Date picker: same calendar + text input as v1, but non-work-days are
//     disabled in the calendar (marked gray via disabledDates) and rejected
//     in validation. Default date jumps forward to the next work day.
//   - Time slot picker: horizontal FlatList of time chips generated by
//     generateSlots(). Available slots are teal; already-booked slots are
//     gray and unselectable. Refreshes when the date or type changes.
//   - Schedule settings are loaded once on open and cached in state.
//   - onSave receives (customerId, { date, notes, type }) where date is an
//     ISO string at the selected appointment start time (not noon placeholder).
//   - State resets on each open via useEffect on visible prop.
//
// CHANGE LOG:
// v1.0  2026-04-10  Claude  Initial implementation
// v1.1  2026-04-10  Claude  Centered overlay instead of bottom sheet
// v2.0  2026-04-17  Claude  Full scheduling engine integration
//       - Added appointment type selector (Service / Install)
//       - Added time slot picker driven by generateSlots()
//       - Date defaults to next work day; non-work days rejected in validation
//         and marked disabled in calendar picker
//       - Scheduling settings loaded from scheduleSettings.js on each open
//       - onSave now passes { date (timed ISO string), notes, type }
//       [updated ARCHITECTURE]
// =============================================================================

import React, { useState, useRef, useMemo, useEffect, useCallback } from 'react';
import {
  View,
  Text,
  TextInput,
  Pressable,
  Modal,
  StyleSheet,
  Alert,
  KeyboardAvoidingView,
  Platform,
  FlatList,
  ScrollView,
  ActivityIndicator,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Calendar } from 'react-native-calendars';
import { useTheme } from '../styles/theme';
import { FontSize } from '../styles/typography';
import {
  getScheduleSettings,
  generateSlots,
  isWorkDay,
  nextWorkDay,
  formatDuration,
  SCHEDULE_DEFAULTS,
} from '../utils/scheduleSettings';

// ── Helpers ───────────────────────────────────────────────────────────────────

function dateParts(d) {
  return {
    dd:   String(d.getDate()).padStart(2, '0'),
    mm:   String(d.getMonth() + 1).padStart(2, '0'),
    yyyy: String(d.getFullYear()),
  };
}

function toDateKey(d) {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
}

// ── Component ─────────────────────────────────────────────────────────────────

export default function ScheduleServiceModal({ visible, customer, onSave, onClose }) {
  const { theme } = useTheme();
  const styles = useMemo(() => makeStyles(theme), [theme]);

  const [appointmentType, setAppointmentType] = useState('service');
  const [dd, setDd]         = useState('');
  const [mm, setMm]         = useState('');
  const [yyyy, setYyyy]     = useState('');
  const [selectedSlot, setSelectedSlot] = useState(null); // { startTime, endTime, label }
  const [notes, setNotes]   = useState('');
  const [calVisible, setCalVisible] = useState(false);
  const [saving, setSaving] = useState(false);
  const [schedSettings, setSchedSettings]   = useState(SCHEDULE_DEFAULTS);
  const [slots, setSlots]                   = useState([]);
  const [slotsLoading, setSlotsLoading]     = useState(false);

  const mmRef   = useRef(null);
  const ddRef   = useRef(null);
  const yyyyRef = useRef(null);

  // Reset state on each open
  useEffect(() => {
    if (!visible) return;

    getScheduleSettings().then((s) => {
      setSchedSettings(s);
      const tomorrow = new Date();
      tomorrow.setDate(tomorrow.getDate() + 1);
      const firstWorkDay = nextWorkDay(tomorrow, s.workDays);
      const p = dateParts(firstWorkDay);
      setMm(p.mm);
      setDd(p.dd);
      setYyyy(p.yyyy);
      setAppointmentType('service');
      setSelectedSlot(null);
      setNotes('');
      setSaving(false);
    });
  }, [visible]);

  // Regenerate time slots when date or type changes
  const parsedDate = useMemo(() => {
    const y = parseInt(yyyy, 10);
    const m = parseInt(mm, 10);
    const d = parseInt(dd, 10);
    if (
      !isNaN(y) && !isNaN(m) && !isNaN(d) &&
      y >= 2000 && y <= 2200 && m >= 1 && m <= 12 && d >= 1 && d <= 31
    ) {
      const parsed = new Date(y, m - 1, d);
      if (parsed.getFullYear() === y && parsed.getMonth() === m - 1 && parsed.getDate() === d) {
        return parsed;
      }
    }
    return null;
  }, [dd, mm, yyyy]);

  const refreshSlots = useCallback(() => {
    if (!parsedDate) { setSlots([]); return; }
    if (!isWorkDay(parsedDate, schedSettings.workDays)) { setSlots([]); return; }

    setSlotsLoading(true);
    const allScheduled = customer?.scheduledServices || [];
    const generated = generateSlots(parsedDate, appointmentType, allScheduled, schedSettings);
    setSlots(generated);
    setSelectedSlot(null);
    setSlotsLoading(false);
  }, [parsedDate, appointmentType, schedSettings, customer]);

  useEffect(() => {
    refreshSlots();
  }, [refreshSlots]);

  // Calendar helpers
  const calSelectedDate = parsedDate ? toDateKey(parsedDate) : '';

  const calMarked = useMemo(() => {
    if (!calSelectedDate) return {};
    return { [calSelectedDate]: { selected: true, selectedColor: theme.scheduled } };
  }, [calSelectedDate, theme.scheduled]);

  const calTheme = useMemo(() => ({
    backgroundColor:            theme.surface,
    calendarBackground:         theme.surface,
    textSectionTitleColor:      theme.textMuted,
    selectedDayBackgroundColor: theme.scheduled,
    selectedDayTextColor:       '#ffffff',
    todayTextColor:             theme.scheduled,
    dayTextColor:               theme.text,
    textDisabledColor:          theme.border,
    arrowColor:                 theme.scheduled,
    monthTextColor:             theme.text,
    textDayFontFamily:          theme.fontBody,
    textMonthFontFamily:        theme.fontUiBold,
    textDayHeaderFontFamily:    theme.fontUiMedium,
    textDayFontSize:            FontSize.sm,
    textMonthFontSize:          FontSize.base,
    textDayHeaderFontSize:      FontSize.xs,
  }), [theme]);

  const handleDayPress = (day) => {
    const [y, m, d] = day.dateString.split('-');
    const date = new Date(parseInt(y), parseInt(m) - 1, parseInt(d));
    if (!isWorkDay(date, schedSettings.workDays)) {
      Alert.alert('Not a Work Day', 'Please select a work day.');
      return;
    }
    setMm(m);
    setDd(d);
    setYyyy(y);
    setCalVisible(false);
  };

  const handleSave = () => {
    if (saving) return;

    if (!parsedDate) {
      Alert.alert('Invalid Date', 'Please enter a valid date.');
      return;
    }

    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const tomorrow = new Date(today);
    tomorrow.setDate(tomorrow.getDate() + 1);
    if (parsedDate < tomorrow) {
      Alert.alert('Invalid Date', 'Scheduled date must be tomorrow or later.');
      return;
    }

    if (!isWorkDay(parsedDate, schedSettings.workDays)) {
      Alert.alert('Not a Work Day', 'Please choose a work day.');
      return;
    }

    if (!selectedSlot) {
      Alert.alert('No Time Selected', 'Please select an available time slot.');
      return;
    }

    setSaving(true);
    onSave(customer.id, {
      date:  selectedSlot.startTime.toISOString(),
      notes: notes.trim(),
      type:  appointmentType,
    });
  };

  const isWorkDayDate = parsedDate ? isWorkDay(parsedDate, schedSettings.workDays) : false;
  const availableCount = slots.filter((s) => s.available).length;
  const durationLabel = formatDuration(
    appointmentType === 'install' ? schedSettings.installMins : schedSettings.serviceMins,
  );

  return (
    <Modal
      visible={visible}
      transparent
      animationType="fade"
      onRequestClose={onClose}
    >
      <KeyboardAvoidingView
        style={styles.overlay}
        behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
      >
        <Pressable style={styles.backdrop} onPress={onClose} />

        <ScrollView
          style={styles.sheetScroll}
          contentContainerStyle={styles.sheet}
          keyboardShouldPersistTaps="handled"
          showsVerticalScrollIndicator={false}
        >
          {/* ── Header ── */}
          <View style={styles.header}>
            <View style={styles.headerLeft}>
              <Ionicons name="calendar" size={20} color={theme.scheduled} style={styles.headerIcon} />
              <View>
                <Text style={styles.title}>Schedule Service</Text>
                {customer && (
                  <Text style={styles.subtitle} numberOfLines={1}>{customer.name}</Text>
                )}
              </View>
            </View>
            <Pressable onPress={onClose} hitSlop={12}>
              <Ionicons name="close" size={22} color={theme.textSecondary} />
            </Pressable>
          </View>

          {/* ── Appointment type ── */}
          <Text style={styles.label}>Type</Text>
          <View style={styles.typeRow}>
            <Pressable
              style={[styles.typeChip, appointmentType === 'service' && styles.typeChipActive]}
              onPress={() => setAppointmentType('service')}
            >
              <Ionicons
                name="construct-outline"
                size={15}
                color={appointmentType === 'service' ? '#fff' : theme.textSecondary}
                style={styles.typeIcon}
              />
              <Text style={[styles.typeText, appointmentType === 'service' && styles.typeTextActive]}>
                Service
              </Text>
              <Text style={[styles.typeDur, appointmentType === 'service' && styles.typeDurActive]}>
                {formatDuration(schedSettings.serviceMins)}
              </Text>
            </Pressable>

            <Pressable
              style={[styles.typeChip, appointmentType === 'install' && styles.typeChipActive]}
              onPress={() => setAppointmentType('install')}
            >
              <Ionicons
                name="home-outline"
                size={15}
                color={appointmentType === 'install' ? '#fff' : theme.textSecondary}
                style={styles.typeIcon}
              />
              <Text style={[styles.typeText, appointmentType === 'install' && styles.typeTextActive]}>
                Install
              </Text>
              <Text style={[styles.typeDur, appointmentType === 'install' && styles.typeDurActive]}>
                {formatDuration(schedSettings.installMins)}
              </Text>
            </Pressable>
          </View>

          {/* ── Date ── */}
          <Text style={styles.label}>Date</Text>
          <View style={styles.dateRow}>
            <View style={styles.dateSegmentWrap}>
              <TextInput
                ref={mmRef}
                style={styles.dateBox}
                value={mm}
                onChangeText={(v) => {
                  const clean = v.replace(/\D/g, '').slice(0, 2);
                  setMm(clean);
                  if (clean.length === 2) ddRef.current?.focus();
                }}
                keyboardType="number-pad"
                maxLength={2}
                placeholder="MM"
                placeholderTextColor={theme.placeholder}
              />
              <Text style={styles.dateSegmentLabel}>Month</Text>
            </View>

            <Text style={styles.dateSep}>/</Text>

            <View style={styles.dateSegmentWrap}>
              <TextInput
                ref={ddRef}
                style={styles.dateBox}
                value={dd}
                onChangeText={(v) => {
                  const clean = v.replace(/\D/g, '').slice(0, 2);
                  setDd(clean);
                  if (clean.length === 2) yyyyRef.current?.focus();
                }}
                keyboardType="number-pad"
                maxLength={2}
                placeholder="DD"
                placeholderTextColor={theme.placeholder}
              />
              <Text style={styles.dateSegmentLabel}>Day</Text>
            </View>

            <Text style={styles.dateSep}>/</Text>

            <View style={[styles.dateSegmentWrap, styles.dateSegmentYear]}>
              <TextInput
                ref={yyyyRef}
                style={[styles.dateBox, styles.dateBoxYear]}
                value={yyyy}
                onChangeText={(v) => setYyyy(v.replace(/\D/g, '').slice(0, 4))}
                keyboardType="number-pad"
                maxLength={4}
                placeholder="YYYY"
                placeholderTextColor={theme.placeholder}
              />
              <Text style={styles.dateSegmentLabel}>Year</Text>
            </View>

            <Pressable
              style={styles.calIcon}
              onPress={() => setCalVisible(true)}
              accessibilityLabel="Open date picker"
            >
              <Ionicons name="calendar-outline" size={22} color={theme.scheduled} />
            </Pressable>
          </View>

          {/* ── Time slots ── */}
          <Text style={styles.label}>Time</Text>
          {slotsLoading ? (
            <ActivityIndicator size="small" color={theme.scheduled} style={{ marginBottom: 16 }} />
          ) : !parsedDate || !isWorkDayDate ? (
            <View style={styles.noSlots}>
              <Text style={styles.noSlotsText}>
                {!parsedDate ? 'Enter a date above' : 'Not a work day — choose another date'}
              </Text>
            </View>
          ) : slots.length === 0 ? (
            <View style={styles.noSlots}>
              <Text style={styles.noSlotsText}>No slots fit in the work day for this duration</Text>
            </View>
          ) : availableCount === 0 ? (
            <View style={styles.noSlots}>
              <Text style={styles.noSlotsText}>All slots booked for this date</Text>
            </View>
          ) : (
            <FlatList
              data={slots}
              keyExtractor={(_, idx) => String(idx)}
              horizontal
              showsHorizontalScrollIndicator={false}
              style={styles.slotList}
              contentContainerStyle={styles.slotListContent}
              renderItem={({ item }) => {
                const isSelected = selectedSlot?.startTime?.getTime() === item.startTime.getTime();
                return (
                  <Pressable
                    style={[
                      styles.slotChip,
                      item.available  && styles.slotChipAvailable,
                      isSelected      && styles.slotChipSelected,
                      !item.available && styles.slotChipBooked,
                    ]}
                    onPress={() => item.available && setSelectedSlot(item)}
                    disabled={!item.available}
                  >
                    <Text
                      style={[
                        styles.slotText,
                        item.available  && styles.slotTextAvailable,
                        isSelected      && styles.slotTextSelected,
                        !item.available && styles.slotTextBooked,
                      ]}
                    >
                      {item.label}
                    </Text>
                  </Pressable>
                );
              }}
            />
          )}

          {selectedSlot && (
            <Text style={styles.slotMeta}>
              {selectedSlot.label} — {durationLabel}
              {schedSettings.travelBefore > 0 || schedSettings.travelAfter > 0
                ? ` · ${schedSettings.travelBefore > 0 ? schedSettings.travelBefore + ' min travel before' : ''}${schedSettings.travelBefore > 0 && schedSettings.travelAfter > 0 ? ', ' : ''}${schedSettings.travelAfter > 0 ? schedSettings.travelAfter + ' min travel after' : ''}`
                : ''}
            </Text>
          )}

          {/* ── Notes ── */}
          <Text style={styles.label}>Notes</Text>
          <TextInput
            style={styles.notesInput}
            value={notes}
            onChangeText={setNotes}
            placeholder="Optional notes…"
            placeholderTextColor={theme.placeholder}
            multiline
            numberOfLines={3}
            textAlignVertical="top"
          />

          {/* ── Save button ── */}
          <Pressable
            style={({ pressed }) => [
              styles.saveBtn,
              pressed && styles.saveBtnPressed,
              saving  && styles.saveBtnDisabled,
            ]}
            onPress={handleSave}
            disabled={saving}
          >
            <Ionicons name="calendar-outline" size={18} color="#fff" style={styles.saveBtnIcon} />
            <Text style={styles.saveBtnText}>
              {saving ? 'Scheduling…' : 'Schedule Service'}
            </Text>
          </Pressable>
        </ScrollView>
      </KeyboardAvoidingView>

      {/* ── Calendar picker (nested modal) ── */}
      <Modal
        visible={calVisible}
        transparent
        animationType="fade"
        onRequestClose={() => setCalVisible(false)}
      >
        <Pressable style={styles.calOverlay} onPress={() => setCalVisible(false)}>
          <Pressable style={styles.calCard} onPress={() => {}}>
            <View style={styles.calHeader}>
              <Text style={styles.calTitle}>Pick a Date</Text>
              <Pressable onPress={() => setCalVisible(false)} hitSlop={12}>
                <Ionicons name="close" size={22} color={theme.textSecondary} />
              </Pressable>
            </View>
            <Calendar
              current={calSelectedDate || undefined}
              minDate={toDateKey(new Date(Date.now() + 86400000))}
              markedDates={calMarked}
              onDayPress={handleDayPress}
              theme={calTheme}
              enableSwipeMonths
              renderArrow={(direction) => (
                <Ionicons
                  name={direction === 'left' ? 'chevron-back' : 'chevron-forward'}
                  size={26}
                  color={theme.scheduled}
                />
              )}
            />
          </Pressable>
        </Pressable>
      </Modal>
    </Modal>
  );
}

function makeStyles(theme) {
  return StyleSheet.create({
    overlay: {
      flex:            1,
      justifyContent:  'center',
      alignItems:      'center',
      backgroundColor: 'rgba(0,0,0,0.45)',
      paddingHorizontal: 20,
    },
    backdrop: {
      ...StyleSheet.absoluteFillObject,
    },
    sheetScroll: {
      width:         '100%',
      maxHeight:     '92%',
    },
    sheet: {
      backgroundColor: theme.surface,
      borderRadius:    20,
      padding:         24,
    },
    // ── Header ──
    header: {
      flexDirection:  'row',
      justifyContent: 'space-between',
      alignItems:     'flex-start',
      marginBottom:    18,
    },
    headerLeft: {
      flexDirection: 'row',
      alignItems:    'center',
      gap:            10,
    },
    headerIcon: {
      marginTop: 2,
    },
    title: {
      fontFamily: theme.fontHeading,
      fontSize:   FontSize.lg,
      color:      theme.text,
    },
    subtitle: {
      fontFamily: theme.fontBody,
      fontSize:   FontSize.sm,
      color:      theme.textMuted,
      marginTop:   2,
    },
    label: {
      fontFamily:    theme.fontUiBold,
      fontSize:      FontSize.xs,
      color:         theme.textSecondary,
      textTransform: 'uppercase',
      letterSpacing:  0.6,
      marginBottom:   8,
    },
    // ── Type selector ──
    typeRow: {
      flexDirection: 'row',
      gap:            10,
      marginBottom:   18,
    },
    typeChip: {
      flex:            1,
      flexDirection:   'row',
      alignItems:      'center',
      justifyContent:  'center',
      paddingVertical: 10,
      borderRadius:    10,
      backgroundColor: theme.inputBg,
      borderWidth:     1.5,
      borderColor:     theme.border,
      gap:              5,
    },
    typeChipActive: {
      backgroundColor: theme.scheduled,
      borderColor:     theme.scheduled,
    },
    typeIcon: {},
    typeText: {
      fontFamily: theme.fontBodyMedium,
      fontSize:   FontSize.sm,
      color:      theme.textSecondary,
    },
    typeTextActive: {
      color: '#fff',
    },
    typeDur: {
      fontFamily: theme.fontBody,
      fontSize:   FontSize.xs,
      color:      theme.textMuted,
    },
    typeDurActive: {
      color: 'rgba(255,255,255,0.75)',
    },
    // ── Date row ──
    dateRow: {
      flexDirection: 'row',
      alignItems:    'flex-end',
      marginBottom:  18,
      gap:            4,
    },
    dateSegmentWrap: {
      alignItems: 'center',
    },
    dateSegmentYear: {
      flex: 1,
    },
    dateBox: {
      width:             56,
      borderWidth:        1.5,
      borderColor:       theme.inputBorder,
      borderRadius:      10,
      paddingVertical:   10,
      paddingHorizontal:  8,
      textAlign:         'center',
      fontFamily:        theme.fontBodyMedium,
      fontSize:          FontSize.base,
      color:             theme.text,
      backgroundColor:   theme.inputBg,
    },
    dateBoxYear: {
      width: '100%',
    },
    dateSegmentLabel: {
      fontFamily: theme.fontUi,
      fontSize:   FontSize.xxs,
      color:      theme.textMuted,
      marginTop:   4,
    },
    dateSep: {
      fontFamily:   theme.fontBodyBold,
      fontSize:     FontSize.lg,
      color:        theme.textMuted,
      marginBottom: 18,
    },
    calIcon: {
      marginBottom: 16,
      marginLeft:    8,
    },
    // ── Time slots ──
    noSlots: {
      paddingVertical: 12,
      marginBottom:    14,
    },
    noSlotsText: {
      fontFamily: theme.fontBody,
      fontSize:   FontSize.sm,
      color:      theme.textMuted,
      fontStyle:  'italic',
    },
    slotList: {
      marginBottom: 4,
    },
    slotListContent: {
      gap:         8,
      paddingRight: 4,
    },
    slotChip: {
      paddingHorizontal: 14,
      paddingVertical:   9,
      borderRadius:      20,
      borderWidth:       1.5,
      borderColor:       theme.border,
      backgroundColor:   theme.inputBg,
    },
    slotChipAvailable: {
      borderColor:     theme.scheduled,
      backgroundColor: theme.scheduled + '18',
    },
    slotChipSelected: {
      backgroundColor: theme.scheduled,
      borderColor:     theme.scheduled,
    },
    slotChipBooked: {
      opacity: 0.4,
    },
    slotText: {
      fontFamily: theme.fontBodyMedium,
      fontSize:   FontSize.sm,
      color:      theme.textMuted,
    },
    slotTextAvailable: {
      color: theme.scheduled,
    },
    slotTextSelected: {
      color: '#ffffff',
    },
    slotTextBooked: {
      color: theme.textMuted,
    },
    slotMeta: {
      fontFamily:   theme.fontBody,
      fontSize:     FontSize.xs,
      color:        theme.textMuted,
      marginTop:     6,
      marginBottom: 14,
    },
    // ── Notes ──
    notesInput: {
      borderWidth:       1.5,
      borderColor:       theme.inputBorder,
      borderRadius:      10,
      paddingHorizontal: 14,
      paddingVertical:   10,
      fontFamily:        theme.fontBody,
      fontSize:          FontSize.base,
      color:             theme.text,
      backgroundColor:   theme.inputBg,
      minHeight:         72,
      marginBottom:      22,
    },
    // ── Save button ──
    saveBtn: {
      flexDirection:     'row',
      alignItems:        'center',
      justifyContent:    'center',
      backgroundColor:   theme.scheduled,
      borderRadius:      12,
      paddingVertical:   14,
      paddingHorizontal: 20,
    },
    saveBtnPressed:  { opacity: 0.85 },
    saveBtnDisabled: { opacity: 0.6  },
    saveBtnIcon: { marginRight: 8 },
    saveBtnText: {
      fontFamily: theme.fontBodyBold,
      fontSize:   FontSize.base,
      color:      '#ffffff',
    },
    // ── Calendar modal ──
    calOverlay: {
      flex:            1,
      backgroundColor: 'rgba(0,0,0,0.5)',
      justifyContent:  'center',
      alignItems:      'center',
    },
    calCard: {
      backgroundColor: theme.surface,
      borderRadius:    16,
      width:           '90%',
      overflow:        'hidden',
    },
    calHeader: {
      flexDirection:  'row',
      justifyContent: 'space-between',
      alignItems:     'center',
      padding:         16,
    },
    calTitle: {
      fontFamily: theme.fontUiBold,
      fontSize:   FontSize.base,
      color:      theme.text,
    },
  });
}
